version: '3.9'

services:

  janus:
    build: .
    image: canyan/janus-gateway:master
    container_name: janus
    hostname: janus
    restart: always
    ports:
      - 8088:8088
      - 8089:8089
      - 8889:8889
    volumes:
      - ./config:/usr/local/etc/janus
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Sao_Paulo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 20s
      placement:
        constraints:
          - node.role==manager
    networks:
      - wpa

  webapp:
    build: ./webapp
    container_name: webapp
    hostname: webapp
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Sao_Paulo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 20s
      placement:
        constraints:
          - node.role==manager
    networks:
      - wpa

networks:
  wpa:
    external: true

