version: '3.9'

services:

  janus:
    image: canyan/janus-gateway:master
    container_name: janus
    hostname: janus
    network_mode: host
    restart: always
    ports:
      - 8088:8088
      - 8188:8188
      - 6000-7000:6000-7000/udp
    volumes:
      - ./config:/usr/local/etc/janus
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Sao_Paulo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 20s
      placement:
        constraints:
          - node.role==manager

